import { PortfolioData } from "./types";

export const defaultPortfolioData: PortfolioData = {
  name: "Nedra Seid",
  role: "Full-Stack Engineer",
  location: "Addis Ababa, Ethiopia",
  bio: "Engineering high-impact web ecosystems, robust backend services, and intelligent automation for real-world solutions.",
  detailedBio: "I am NEDRA SEID a freshman at ETHIOPIAN PUBLIC SERVICE UNIVERCITY and dedicated Full-Stack Engineer based in Addis Ababa, Ethiopia. I specialize in designing and shipping scalable web applications that combine clean architectures with smart interactive workflows. Experienced in developing enterprise platforms, AI integration (using Gemini), and role-based workflows for public and private organizations.",
  socials: {
    github: "https://github.com/nedraseid-dev",
    linkedin: "https://www.linkedin.com/in/nedra-seid-b144ab3b0",
    twitter: "https://x.com/NedraSeid64192",
    email: "nedraseid@gmail.com",
    telegram: "https://t.me/ameteljebbar",
  },
  stats: [
    { label: "Completed Projects", value: "10" },
    { label: "Client Platforms Deployed", value: "15" },
    { label: "System Uptime Guaranteed", value: "99.9%" },
  ],
  projects: [
    {
      id: "qanun",
      title: "Qanun",
      description: "A full-stack legal-tech platform built for the Ethiopian justice system, connecting citizens and lawyers.",
      longDescription: "A full-stack legal-tech platform built for the Ethiopian justice system, connecting citizens and lawyers through a unified case and consultation workflow. It features an AI legal assistant powered by Gemini, along with a complete invite/consultation system, JWT-secured authentication, and role-based case management.",
      image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80",
      tags: ["React", "Node.js", "Gemini AI", "JWT", "Express", "MongoDB"],
      demoUrl: "https://qanun-rust.vercel.app",
      githubUrl: "https://github.com",
      featured: true,
    },
    {
      id: "bizpermit",
      title: "BizPermit Ethiopia",
      description: "Full-stack digital platform built for the Ministry of Trade & Industry to modernize license renewals.",
      longDescription: "BizPermit Ethiopia is a full-stack digital platform built for the Ministry of Trade & Industry to modernize business license renewals across Ethiopia's Federal, City, Sub-city, and Woreda administrative levels. It supports role-based workflows for clerks, inspectors, and business owners, with full Amharic/English bilingual support.",
      image: "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80",
      tags: ["React", "Express", "Node.js", "PostgreSQL", "Bilingual Support"],
      demoUrl: "https://bizpermit.netlify.app",
      githubUrl: "https://github.com",
      featured: true,
    },
    {
      id: "turkey-travel",
      title: "Turkey Travel Agency",
      description: "An engaging, visually driven tourism exploration and booking platform for Turkish destinations.",
      longDescription: "This platform gives users a complete tourism experience of Turkey, designed to showcase the country's rich cultural and historical heritage. Users can explore traditional and iconic destinations from ancient landmarks to culturally significant sites through an engaging, visually driven interface that highlights what makes each location worth visiting. Beyond exploration, the platform bridges inspiration with action: users who are interested in visiting can seamlessly book their flights directly through the app, removing the friction between discovering a destination and actually planning the trip.",
      image: "/src/assets/images/turkey_travel_cappadocia_1784623170289.jpg",
      tags: ["React", "Vite", "Tailwind CSS", "Flight Booking API", "Motion"],
      demoUrl: "https://turkeytravelagency.netlify.app",
      githubUrl: "https://github.com",
      featured: true,
    },
    {
      id: "adv-calc",
      title: "Advanced Calculator",
      description: "A comprehensive calculation tool supporting scientific, trigonometric, and complex operations.",
      longDescription: "An advanced calculator application that goes beyond basic arithmetic, supporting scientific and complex operations such as trigonometric functions, logarithms, exponents, and more. Designed with a clean, intuitive interface for fast and accurate calculations, it's built to handle both everyday math and more advanced computational needs.",
      image: "/src/assets/images/calculator_premium_interface_1784623185738.jpg",
      tags: ["TypeScript", "React", "Tailwind CSS", "Math.js"],
      demoUrl: "https://mycalculator5.netlify.app",
      githubUrl: "https://github.com",
      featured: false,
    },
    {
      id: "weather-app",
      title: "Atmosphere Weather",
      description: "Real-time global weather tracking app powered by the OpenWeatherMap API.",
      longDescription: "A weather application that provides real-time weather data and forecasts for locations worldwide, powered by the OpenWeatherMap API. Built with Node.js and Express, it delivers accurate, up-to-date conditions through a clean and simple interface.",
      image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=800&q=80",
      tags: ["Node.js", "Express", "OpenWeatherMap API", "REST API"],
      demoUrl: "https://myweatherapp5.netlify.app",
      githubUrl: "https://github.com",
      featured: false,
    },
  ],
  skills: [
    { name: "React / Next.js", category: "Frontend", level: 95 },
    { name: "TypeScript", category: "Frontend", level: 92 },
    { name: "Tailwind CSS", category: "Frontend", level: 95 },
    { name: "Node.js / Express", category: "Backend", level: 94 },
    { name: "PostgreSQL & MongoDB", category: "Backend", level: 88 },
    { name: "Gemini AI SDK", category: "Backend", level: 90 },
    { name: "JWT Authentication", category: "Backend", level: 95 },
    { name: "RESTful API Design", category: "Backend", level: 96 },
    { name: "Figma UI/UX", category: "Design", level: 85 },
    { name: "Docker & Deployment", category: "Tools", level: 80 },
    { name: "Git & Team Workflows", category: "Tools", level: 95 },
  ],
  experience: [
    {
      id: "exp-1",
      role: "Full-Stack Software Engineer",
      company: "Freelance & Digital Solutions",
      duration: "2024 - Present",
      description: "Architecting high-fidelity web products for national ministries and private enterprises. Built custom business licensing renewal workflows, legal-tech advisory solutions, and integrated LLM AI assistant features to simplify regulatory systems.",
      tags: ["React", "Express", "Node.js", "Gemini AI", "MongoDB", "PostgreSQL"],
    },
    {
      id: "exp-2",
      role: "Backend Specialist & API Developer",
      company: "LegalTech & GovTech Projects",
      duration: "2023 - 2024",
      description: "Spearheaded secure, robust authentication protocols and JWT systems. Deployed role-based routing systems across federal, city, sub-city, and woreda systems for government client platforms.",
      tags: ["Node.js", "Express", "JWT", "REST APIs", "Bilingual localization"],
    },
    {
      id: "exp-3",
      role: "Software Engineering & CyberSecurity Trainee",
      company: "INSA (Information Network Security Administration)",
      duration: "2025 - 2026",
      description: "Acquired depth knowledge in secure software development lifecycle (SSDLC), security frameworks, and threat modeling. Designed and developed secure prototype services and analyzed vulnerabilities under expert security engineers.",
      tags: ["Application Security", "API Hardening", "SSDLC", "Network Security"],
    },
  ],
};
